spring:
#  zipkin:
#    base-url: http://localhost:9411

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6i3853g7l2kux4e.mysql.rds.aliyuncs.com:3306/sh_good_dev?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: dev
    password: D2ev!$456
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
server:
  port: 8940
wechat:
  mini:
    appId: wx38c5134db2f9d99c
    appSercret: 020f87014a76cc45af60cd6c6cc2c312
    defaultUserPassword: Fs29%s/b
  #
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  #    publisher-confirms: true
  #    virtual-host: /