spring:
#  zipkin:
#    base-url: http://localhost:9411

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6i3853g7l2kux4e.mysql.rds.aliyuncs.com:3306/sh_user_dev?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: dev
    password: D2ev!$456
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  rabbitmq:
    host: 106.14.223.118
    port: 5672
    username: mq_admin
    password: Maa1234
    publisher-confirms: true
    virtual-host: dev_vhost
server:
  port: 9010
wechat:
  mini:
    defaultUserPassword: Fs29%s/b
