spring:
#  zipkin:
#    base-url: http://localhost:9411
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6i3853g7l2kux4e.mysql.rds.aliyuncs.com:3306/sh_user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: dev
    password: D2ev!$456
    jpa:
      hibernate:
        ddl-auto: none
        show-sql: true
server:
  port: 8910
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
