spring:
#  zipkin:
#    base-url: http://localhost:9411

  rabbitmq:
    host: 106.14.223.118
    port: 5672
    username: mq_admin
    password: Maa1234
    publisher-confirms: true
    virtual-host: dev_vhost
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6i3853g7l2kux4e.mysql.rds.aliyuncs.com:3306/sh_user_dev?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: dev
    password: D2ev!$456
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
server:
  port: 8920
wechat:
  mini:
    appId: wx38c5134db2f9d99c
    appSercret: 020f87014a76cc45af60cd6c6cc2c312
    defaultUserPassword: Fs29%s/b
    #二维码进入页面
    page: pages/index/index
    width: 430
  pay:
    #微信支付费率
    rate: 0.006
promotion:
  order:
    #推荐奖励
    bonus: 0.15
    #复购折扣
    reBuy: 0.6
file:
  path: /mnt/static
  url: /static